CREATE TABLE liked(
    TWEET_ID				INT NOT NULL,
    USER_ID					NVARCHAR(20) NOT NULL,
    PRIMARY KEY (TWEET_ID, USER_ID),
    FOREIGN KEY (TWEET_ID) REFERENCES twitter.tweet(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES twitter.user(ID) ON DELETE CASCADE)
