CREATE TABLE twitter.tweet(
	ID							INT AUTO_INCREMENT NOT NULL,
	USER_ID						NVARCHAR(20) NOT NULL,
    CONTENT						NVARCHAR(256) NOT NULL,
    POSTAGE						DATE NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES twitter.user(ID))